create table if not exists users (
 id bigint generated by default as identity primary key,
 login text unique not null,
 password_hash text not null,
 alias text unique not null,
 created_at bigint not null
);
create table if not exists sessions (
 token_hash text primary key,
 user_id bigint not null references users(id) on delete cascade,
 expires bigint not null
);
create table if not exists posts (
 id bigint generated by default as identity primary key,
 user_id bigint not null references users(id),
 title text not null,
 body text not null,
 category text not null,
 created_at bigint not null,
 demo integer not null default 0 check (demo in (0, 1)),
 hidden integer not null default 0 check (hidden in (0, 1))
);
create table if not exists comments (
 id bigint generated by default as identity primary key,
 post_id bigint not null references posts(id) on delete cascade,
 user_id bigint not null references users(id),
 body text not null,
 created_at bigint not null
);
create table if not exists votes (
 post_id bigint not null references posts(id) on delete cascade,
 user_id bigint not null references users(id) on delete cascade,
 primary key(post_id, user_id)
);
create table if not exists reports (
 id bigint generated by default as identity primary key,
 post_id bigint not null references posts(id) on delete cascade,
 user_id bigint not null references users(id),
 reason text not null,
 created_at bigint not null,
 unique(post_id, user_id)
);
create table if not exists rate_limits (
 bucket text primary key,
 count integer not null,
 expires bigint not null
);
create table if not exists feed_snapshots (
 token text primary key,
 post_ids text not null,
 policy_version text not null,
 created_at bigint not null,
 expires bigint not null
);
create index if not exists posts_feed on posts(hidden, created_at desc);
create index if not exists comments_post on comments(post_id, created_at);
create index if not exists feed_snapshots_expiry on feed_snapshots(expires);

-- The Flask server is the only data-access path. Block Supabase Data API roles.
alter table users enable row level security;
alter table sessions enable row level security;
alter table posts enable row level security;
alter table comments enable row level security;
alter table votes enable row level security;
alter table reports enable row level security;
alter table rate_limits enable row level security;
alter table feed_snapshots enable row level security;
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

-- Fictional opening-edition stories. They carry no votes or replies.
insert into users(login, password_hash, alias, created_at) values
 ('demo-overcaffeinated-pigeon', 'disabled', 'OvercaffeinatedPigeon', extract(epoch from now())::bigint),
 ('demo-unmuted-stapler', 'disabled', 'UnmutedStapler', extract(epoch from now())::bigint),
 ('demo-quiet-raccoon', 'disabled', 'QuietRaccoon', extract(epoch from now())::bigint),
 ('demo-corporate-potato', 'disabled', 'CorporatePotato', extract(epoch from now())::bigint),
 ('demo-feral-paperclip', 'disabled', 'FeralPaperclip', extract(epoch from now())::bigint)
on conflict (login) do nothing;

insert into posts(user_id, title, body, category, created_at, demo)
select u.id, v.title, v.body, v.category,
       extract(epoch from now())::bigint - v.age_hours * 3600, 1
from (values
 ('OvercaffeinatedPigeon', 'My manager scheduled a meeting to ask why we spend so much time in meetings.', E'Forty-five minutes. Twelve people. A slide titled “Protecting our focus time”.\n\nThe action item? A weekly check-in to track how many meetings we’ve cut. I wish I was making this up. Anyway, see you all at the meeting about the meeting.', 'Manager mayhem', 1),
 ('UnmutedStapler', 'Apparently “we’re a family” means I’m the unpaid therapist.', E'I came here to make spreadsheets. Somehow I’m now mediating a cold war over who changed the shared playlist.\n\nPlease just let me do my extremely medium job and go home at a reasonable hour.', 'Office politics', 2),
 ('QuietRaccoon', 'I closed my laptop at 6. Nothing caught fire.', E'No dramatic exit. No announcement. Just closed it, went for a walk, and ate dinner without refreshing my inbox.\n\nThe next morning, the company was still there. Wild concept. Trying it again tomorrow.', 'Small victories', 3),
 ('CorporatePotato', '“Quick sync” is the biggest lie in the English language.', E'A quick sync became a deep dive, which became a parking lot, which somehow became a sprint.\n\nI’ve been sitting in the same chair for ninety minutes. How is there this much movement and no progress?', 'Meeting purgatory', 4),
 ('FeralPaperclip', 'The burnout workshop has mandatory homework.', E'We have to complete a wellbeing worksheet, log our relaxation goals, and present our personal resilience plan on Friday.\n\nI asked if having less work could be on the plan. Apparently that’s outside the scope of the workshop.', 'HR said what?', 5)
) as v(alias, title, body, category, age_hours)
join users u on u.alias = v.alias
where not exists (select 1 from posts p where p.title = v.title);

